name: Build OpenWrt Firmware

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04  # 使用 ubuntu-22.04 避免潜在的兼容性问题

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential git-core libncurses5-dev zlib1g-dev gawk flex quilt libssl-dev xsltproc libxml-parser-perl mercurial bzr ecj cvs unzip python3 python3-pip wget

    - name: Run build script
      run: |
        export BACKEND_IP="192.168.6.1"
        export THEME="argon"
        export KERNEL_VERSION="6.6"
        export PARTITION_SIZE="2048M"
        export AUTHOR="04543473"
        export CUSTOM_SOFTWARE="vim htop"
        export EXCLUDE_FILES="kmod-usb-storage luci-app-ddns"
        chmod +x Untitled-1.sh
        ./Untitled-1.sh

    - name: Clean up after build
      run: |
        # 删除OpenWrt源码目录以释放空间
        rm -rf openwrt
        # 删除临时文件
        sudo rm -rf /tmp/*
        # 删除APT缓存和包列表
        sudo apt-get clean
        sudo rm -rf /var/lib/apt/lists/*
        # 删除GitHub Actions日志文件
        sudo rm -rf /home/runner/runners/2.321.0/_diag/*
        # 删除GitHub Actions缓存
        sudo rm -rf /home/runner/work/_temp/*
        # 删除不必要的缓存和临时文件
        sudo rm -rf /home/runner/work/_actions/*

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false

    - name: Upload firmware to GitHub Releases
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./openwrt/bin/targets/x86/64/openwrt-x86-64-generic-squashfs-combined.img.gz
        asset_name: openwrt-x86-64-generic-squashfs-combined-ipv4.img.gz
        asset_content_type: application/gzip

    - name: Clean up after release
      run: |
        # 删除固件文件以释放空间
        rm -rf openwrt/bin/targets/x86/64/*
        # 删除临时文件
        sudo rm -rf /tmp/*
        # 删除APT缓存和包列表
        sudo apt-get clean
        sudo rm -rf /var/lib/apt/lists/*
        # 删除GitHub Actions日志文件
        sudo rm -rf /home/runner/runners/2.321.0/_diag/*
        # 删除GitHub Actions缓存
        sudo rm -rf /home/runner/work/_temp/*
        # 删除不必要的缓存和临时文件
        sudo rm -rf /home/runner/work/_actions/*
