name: Build OpenWrt Firmware

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential git-core libncurses5-dev zlib1g-dev gawk flex quilt libssl-dev xsltproc libxml-parser-perl mercurial bzr ecj cvs unzip python3 python3-pip wget

    - name: Run build script
      run: |
        chmod +x Untitled-1.sh
        ./Untitled-1.sh

    - name: Upload firmware to GitHub Releases
      uses: svenstaro/upload-release-action@v2-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: openwrt/bin/targets/x86/64/openwrt-x86-64-generic-squashfs-combined.img.gz
        asset_name: openwrt-x86-64-generic-squashfs-combined.img.gz
        tag: ${{ github.ref_name }}
        overwrite: true
